### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by dominicsayers** [mislav/rfc#9]
Not 100% sure about this myself, but perhaps it would be good to allow comments and conversation about the RFCs?

In theory there's nothing stopping interested parties getting involved with the IETF directly, but in practice it's a pretty forbidding clique.

Allowing comments might actually tempt people with an opinion but little spare time to have their say about these important documents.

**Comment by juaristi** [comment]
Although a per-RFC comment section would not make much sense as you point out @mislav, it would be good to provide some sort of linking to the specific part of an RFC's text a certain comment is referring to (think of GitHub's line commenting feature, but with paragraphs, instead of single lines). Unfortunately, RFCs are sometimes loosely explained and experienced people could use this feature to clear the doubts that might arise regarding the interpretation of a certain RFC.
